version: "3.8"
name: ${CONTAINER_NAME}
services:
  prod:
    container_name: ${CONTAINER_NAME}
    image: ${CONTAINER_NAME}:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: bash -c "chown -R www-data /var/www/html && (php-fpm &) && nginx -g 'daemon off;'"
    restart: always
    env_file: .env
    environment:
      - DB_HOST=wordpressdb-test.c5st5fhnmcyv.us-east-1.rds.amazonaws.com:3306
      - DB_CONNECTION=mysql
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html
      - ./nginx-default.conf:/etc/nginx/sites-available/default

