version: "3.8"
name: ${CONTAINER_NAME}
services:
  prod:
    container_name: ${CONTAINER_NAME}
    image: mysql:8.0.28
    env_file: .env
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./backups:/backups
